### PR TITLE
~~ESLint just banned me.~~ Actually my Internet might be haunted

### PR DESCRIPTION
**Pull request by Alhadis**
Just pushing this to see if it shows up in eslint/eslint#13407 after they banned me for asking something they couldn't answer.

EDIT: Yep, it does. Hey @kaicataldo, are you still going to show me evidence of the words "blacklist" and "whitelist' managing to offend people? I'm honestly curious.

Feel free to never bother answering this, I'll wait.

### CODE REVIEW

**Comment by kaicataldo** [comment]
You aren't blocked by me or the ESLint organization, so not sure what you're referring to here.

**Comment by Alhadis** [comment]
Care to explain this, then?


That's what a banned user sees after they've been blocked. I'm not pissed or anything, I'm just mildly amused by either the unneeded banning, or the ironic timing of an apparent site glitch.

**Comment by platinumazure** [comment]
@Alhadis As Kai said earlier, ESLint didn't block you. I would suggest contacting GitHub Support about this; either it's a bug, or they can explain if some broader action was taken against your account. Good luck!

**Comment by Alhadis** [comment]
Oh man, you're right. I could edit my comments on that thread, and the same panel isn't showing when I open another issue.

😂  If this is a bug, its timing was certainly awkward.

**Pull request closed without merging**
